[build]
  command = ""
  publish = "."

[functions]
  directory = "netlify/functions"
  node_bundler = "esbuild"

# Mapear /api/* -> Functions (OK usar /.netlify no "to")
[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

# (Opcional) atalho direto só para /api/simular
[[redirects]]
  from = "/api/simular"
  to = "/.netlify/functions/simular"
  status = 200

# SPA catch-all (fica por ÚLTIMO)
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
